# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160430_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championdata',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
