# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160430_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championdata',
            name='time_played',
        ),
    ]
