# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_championdata_time_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championdata',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='cs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='double_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='first_blood_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='highest_grade',
            field=models.CharField(default='0', max_length=2),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='inhibitor_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='largest_cs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='largest_killing_spree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='mastery_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='mastery_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='penta_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='quadra_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='triple_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='turret_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='ward_kills',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='wards_placed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championdata',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='game_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='summoner',
            name='profile_icon_id',
            field=models.IntegerField(),
        ),
    ]
