# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160430_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='region',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
